language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t wenlizhang/docker-react -f Dockerfile.dev .

script:

  - docker run -e CI=true wenlizhang/docker-react npm run test