sudo: required
services:
  - docker
# before create the image, the needed steps
before_install:
  - docker build -t wenlizhang/docker-react -f Dockerfile.dev .
# commands for running the tests
script:
# never exist p/t/q???
# so -- --coverage
  - docker run wenlizhang/docker-react npm run test -- --coverage