# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id>
version: '3'
services:
  web:
    build:
      context: .
      # figure out the dockerfile to build the image 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # skip mapping node_modules
      - /app/node_modules
      # map 
      - .:/app
  tests:
    build:
      context: .
      # figure out the dockerfile to build the image 
      dockerfile: Dockerfile.dev
    volumes:
      # skip mapping node_modules
      - /app/node_modules
      # map 
      - .:/app
    command: ["npm", "run", "test"]

    
    